# Generated by Django 5.0 on 2023-12-09 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gruppa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Semeystvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Rastenie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=50)),
                ('opublikovano', models.BooleanField(blank=True, default=False)),
                ('data_izmen', models.DateTimeField(blank=True, null=True)),
                ('izobrazhenie', models.CharField(blank=True, max_length=200, null=True)),
                ('opisanie', models.TextField(blank=True, null=True)),
                ('temperatura', models.TextField(blank=True, null=True)),
                ('osveshenie', models.TextField(blank=True, null=True)),
                ('poliv', models.TextField(blank=True, null=True)),
                ('udobrenie', models.TextField(blank=True, null=True)),
                ('vlazhnost', models.TextField(blank=True, null=True)),
                ('peresadka', models.TextField(blank=True, null=True)),
                ('razmnozhenie', models.TextField(blank=True, null=True)),
                ('gruppi', models.ManyToManyField(to='plants.gruppa')),
                ('semeystvo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plants.semeystvo')),
            ],
        ),
    ]
