# Generated by Django 5.0 on 2023-12-22 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_rastenie_gruppi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=50)),
                ('psswd', models.CharField(max_length=30)),
                ('admn', models.BooleanField(blank=True, default=False)),
                ('izbrannoe', models.ManyToManyField(blank=True, to='plants.rastenie')),
            ],
        ),
    ]
